---
title: "temporary title"
header-includes:
- \usepackage{graphicx}
- \usepackage{float}
date: '2017-04-05'
output:
  bookdown::pdf_document2:
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 2
  bookdown::html_document2:
    css: style.css
    number_sections: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
subtitle: 'MTKG776: Applied Probability Models in Marketing'
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.align = 'center', size = 'small', fig.pos = 'H',
                      fig.width = 6, fig.height = 3.5)

knitr::knit_hooks$set(
          size = function(before, options, envir) {
                  if (before) return(paste0("\n \\", options$size, "\n\n"))
                  else return("\n\n \\normalsize \n")
                  }
          , inline = function(x) {if(!is.numeric(x)){ x }else{ prettyNum(round(x,2), big.mark=",") } }
          )
```

```{r report-load-packages, results = 'hide', include = FALSE}
pacman::p_load(tidyverse, forcats, pander, stringr, lubridate, jrfTools, extrafont, RcppRoll, ggrepel, tm, pdftools)
```

```{r report-additional-setup, include = FALSE}
options(scipen=999)
panderOptions('digits', 8)
panderOptions('round', 4)
panderOptions('keep.trailing.zeros', TRUE)
```

```{r report-wordcount}
fn_cound_words <- function(file) {
  txt <- pdf_text(file)
  corp1 <- VCorpus(VectorSource(txt))
  corp2 <- tm_map(corp1, stripWhitespace)
  corp3 <- tm_map(corp2, removePunctuation)
  corp4 <- tm_map(corp3, content_transformer(tolower))
  corp5 <- tm_map(corp4, removeNumbers)
  dtm <- TermDocumentMatrix(corp5)
  dtm %>% as.matrix() %>% sum()
}

n_words <- fn_cound_words(paste0("mktg776_p2.pdf"))
```

**Word Count**: `r n_words`

# Executive Summary